### ISSUE TITLE
Default User/Password Not Working

### ISSUE THREAD

**Issue by DennisFaucher** [pozgo/docker-snorby#4]
Hi, just ran the docker image and used my existing MariaDB. When I try to login with snorby@snorby.org/snorby, the docker log returns this:

cache: [POST /users/login] invalidate, pass

Am I using the wrong user/password or is snorby not accessing MariaDB correctly. My run command is:

sudo docker run -d --name snorby -p 3000:3000 --env="DB_ADDRESS=127.0.0.1" --env="DB_USER=root" --env="DB_PASS=mysql" polinux/snorby

Thanks in advance.

**Comment by pozgo** [comment]
you shouldn't use the `127.0.0.1` address as it's referring localhost inside of the snorby container. 

I would rather use `docker-compose` to deploy this or otherwise use you local machine IP address if your MariaDB is accessible on you local machine. 

ie:

```
docker run -d -p 3306:3306 mariadb:latest

docker run -d -p 3000:000 --env=--env="DB_ADDRESS=192.168.1.100" --env="DB_USER=root" --env="DB_PASS=mysql" polinux/snorby
```
assuming your local address is `192.168.1.100`

**Comment by DennisFaucher** [comment]
Thank you. I'll give it a go and then close.

**Comment by DennisFaucher** [comment]
Closing
